/**
 * Bake image files into ASCII art for the hero code-art layer.
 *
 * Usage:
 *   npm run ascii -- <image> [width] [label]
 *   npm run ascii -- ./photo.jpg 46 photo.jpg
 *
 * Or convert every image in a folder:
 *   npm run ascii -- ./art-src
 *
 * Prints the ASCII to stdout and also writes lib/baked-ascii.ts as an array of
 * { label, art } the hero imports. Existing entries are preserved unless a
 * label collides.
 */
import "../lib/load-env";
import sharp from "sharp";
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { resolve, basename, extname } from "node:path";
import { pixelsToAscii, ASCII_RAMP } from "../lib/ascii";

const OUT = resolve(process.cwd(), "lib/baked-ascii.ts");

async function convert(file: string, width: number): Promise<string> {
  // Decode to raw RGBA at a manageable size for sampling.
  const img = sharp(file).resize({ width: 320, withoutEnlargement: true });
  const { data, info } = await img
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  return pixelsToAscii(
    new Uint8ClampedArray(data),
    info.width,
    info.height,
    { width, ramp: ASCII_RAMP }
  );
}

type Entry = { label: string; art: string };

function loadExisting(): Entry[] {
  if (!existsSync(OUT)) return [];
  try {
    const txt = readFileSync(OUT, "utf8");
    const m = txt.match(/export const BAKED_ASCII[^=]*=\s*(\[[\s\S]*\]);/);
    if (!m) return [];
    // eslint-disable-next-line no-eval
    return eval(m[1]) as Entry[];
  } catch {
    return [];
  }
}

function write(entries: Entry[]) {
  const body = entries
    .map(
      (e) =>
        `  {\n    label: ${JSON.stringify(e.label)},\n    art: ${JSON.stringify(
          e.art
        )},\n  },`
    )
    .join("\n");
  const file = `/**
 * Baked ASCII art for the hero code-art layer. Generated by scripts/img-to-ascii.ts.
 * Do not edit by hand; run: npm run ascii -- <image> [width] [label]
 */
export type BakedAscii = { label: string; art: string };

export const BAKED_ASCII: BakedAscii[] = [
${body}
];
`;
  writeFileSync(OUT, file);
}

async function main() {
  const args = process.argv.slice(2);
  if (!args.length) {
    console.error("Usage: npm run ascii -- <image|folder> [width] [label]");
    process.exit(1);
  }
  const target = resolve(args[0]);
  const width = Number(args[1]) || 46;
  const labelArg = args[2];

  const files: string[] = [];
  if (statSync(target).isDirectory()) {
    for (const f of readdirSync(target)) {
      if (/\.(png|jpe?g|webp|gif|bmp|avif)$/i.test(f)) {
        files.push(resolve(target, f));
      }
    }
  } else {
    files.push(target);
  }
  if (!files.length) {
    console.error("No images found.");
    process.exit(1);
  }

  const existing = loadExisting();
  const byLabel = new Map(existing.map((e) => [e.label, e]));

  for (const file of files) {
    const label =
      files.length === 1 && labelArg
        ? labelArg
        : basename(file, extname(file));
    const art = await convert(file, width);
    byLabel.set(label, { label, art });
    console.log(`\n=== ${label} (${width} cols) ===`);
    console.log(art);
  }

  write([...byLabel.values()]);
  console.log(`\nWrote ${byLabel.size} entries to lib/baked-ascii.ts`);
}

main().catch((e) => {
  console.error("ERROR:", e.message ?? e);
  process.exit(1);
});
